version: '3.8'

services:
  unalsuba:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
    networks:
      - unalsuba-network

networks:
  unalsuba-network:
    driver: bridge
